---
name: Move new issues into Backlog

on:
  issues:
    types: [opened, reopened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: metr1c
          column: 'ğŸ—ƒï¸ Backlog'
          repo-token: ${{ secrets.GITHUB_TOKEN }}